### ISSUE TITLE
Please add a Conda environment.yml for linux-64

### ISSUE THREAD

**Issue by okorn-src** [jarny/iscandar#1]
I had issues with versions not existing for:

1. appnope
2. gcc
3. gettext
4. isl

And a conflict for QT / jpeg libraries:
`UnsatisfiableError: The following specifications were found to be in conflict:
  jpeg 9b 0
  qt 5.6.2 2 -> jpeg 8*
Use "conda info <package>" to see the dependencies for each package.
`

I was able to resolve some of the libraries by selecting similar versions that exist in Anaconda for linux-64 but the conflict above involves a major version difference in required jpeg library - so this is something I'm not equipped to make a call on given I don't know the Iscandar code.

Any help appreciated, cheers.

**Comment by jarny** [comment]
Sorry, that version of environment.yml was totally wrong - not sure how that got there, as it had many unnecessary packages. It's been updated now.

**Comment by okorn-src** [comment]
Thanks, this is what I'm getting now:

`$ conda env create -f environment.yml`

`Fetching package metadata
NoPackagesFoundError: Package missing in current linux-64 channels: 
  ca-certificates 2017.08.26 ha1e5d58_0
`

Also: I removed the "prefix" line from environment.yml which is probably not meant to be there!

**Comment by jarny** [comment]
I'm not sure what that ca-certificates does (nor for the certifi=... in the next line for that matter). Would you be able to delete the line and try again? It seems to work for me fine without it, but it would be good to see if it's the same elsewhere.

Apparently the prefix line is ignored by conda create (https://stackoverflow.com/questions/41274007/anaconda-export-environment-file <https://stackoverflow.com/questions/41274007/anaconda-export-environment-file>), but I should remove it manually just to be clear.

Thanks - I'll commit again when I know that we have a working environment.

**Comment by okorn-src** [comment]
Thanks, I deleted the certificate packages, it's now complaining about versions of `intel-openmp`, `libcxx` and `libedit` not existing in linux-64 - I think you might want to test this in a 64-bit Linux environment so you can work through the package issues?

**Comment by jarny** [comment]
OK. Will do and let you know. Thanks again.

**Comment by okorn-src** [comment]
Thanks heaps, look forward to testing/feedback to get this sorted.

**Comment by jarny** [comment]
It turns out that conda env export was listing all packages used in the Mac OS version of anaconda. One workaround may be to use miniconda instead of anaconda supplied to the Mac, but it's also easier to manually create a simplified version of the environment.yml, since the requirements for iscandar are quite simple.

**Comment by okorn-src** [comment]
Thanks for updating the environment files, Conda issues have been resolved for Linux-64.
